### ISSUE TITLE
전투 시스템 기획

### ISSUE THREAD

**Issue by unagi11** [TeamJelly/project21#11]

**Comment by unagi11** [comment]
플로우 차트 완성
[https://drive.google.com/file/d/1Pg7k1duYiwb71yUuulfQppFdApdr6Kd0/view?usp=sharing](url)

**Comment by unagi11** [comment]
문서 정리 필요

**Comment by JeHwanYoo** [comment]
관리 되지 않은 이슈라 닫습니다.
