### ISSUE TITLE
스킬, 아이템, 유물 DB구현 방식

### ISSUE THREAD

**Issue by NaTure77** [TeamJelly/project21#19]
제작하게 될 데이터베이스 구현 방식을 의논 해봐야 할 것 같습니다.
의견 남겨주시면 감사하겠습니다.

제가 아는 선에서 방법들을 나열하자면 이정도 인 것 같습니다.
- JSON
- XML
- Binary Formatter
- 클래스 상속 후 개별 클래스 생성(다형성 활용)

다른 선택지도 있는지 찾아보겠습니다.

**Comment by unagi11** [comment]
xml 은 엑셀자료 사용가능하지 않나
json도 많이 쓰는듯
