### ISSUE TITLE
기획서 작성

### ISSUE THREAD

**Issue by unagi11** [TeamJelly/project21#2]

**Comment by shiromarisa** [comment]
상태효과 추가,
직업 공백 채워넣음
사이즈 설명 추가 
유닛 부활과 사망 설명추가
파티원 영입과 해고 설명
전리품 분배 작성

**Comment by unagi11** [comment]
통합기획서에 기획 진행도 표시완료
문서 분리 진행중

**Comment by JeHwanYoo** [comment]
관리 되지 않은 이슈라 닫습니다.
