### ISSUE TITLE
CommonUI 구축

### ISSUE THREAD

**Issue by JeHwanYoo** [TeamJelly/project21#22]

**Comment by JeHwanYoo** [comment]
@NaTure77 프리펩 완성

**Comment by NaTure77** [comment]
@JeHwanYoo

확인했습니다. 현재까지 발견된 이슈를 조심스럽게 올려봅니다.

1. CommonImage에 이미지 교체 기능이 추가되야 될 것 같습니다.
![image](https://user-images.githubusercontent.com/18459135/104114925-213a7b00-534d-11eb-93af-beff7cfcfdbc.png)
: 현재 턴 유닛 정보를 나타내는 창 갱신

2. CommonText의 textMesh가 할당이 안되는 것 같습니다.
: Text 갱신 시 NullReferenceException이 발생.

**Comment by JeHwanYoo** [comment]
@NaTure77 해당 부분 수정 가능한가요?

**Comment by NaTure77** [comment]
@JeHwanYoo 넵 가능합니다. 저녁에 수정하도록 하겠습니다.
