### ISSUE TITLE
전투방에 유닛 프리팹 동적으로 배치

### ISSUE THREAD

**Issue by NaTure77** [TeamJelly/project21#30]
씬 이동 시 파티 유닛정보를 쉽게 보존하기 위한 방법 제안

**1. 전투방의 MVC 패턴 구조를 완성 시키기**
  - 맵, 유닛 오브젝트를 생성/관리하기 위한 Model 스크립트 제안
  - Model: MapGenerator (특별히 떠오르는 이름이 없음..)
  - Viewer: BattleUI
  - Controller: BattleManager

**2. (기존) 프리팹에 Unit 스크립트 추가 → (제안) 프리팹 인스턴스를 Unit에 할당(코드와 모델 분리)**
  - 전투방 입장 시 프리팹 인스턴스 동적으로 생성.
  - Unit.Move: 직접 움직이는 대신 해당 프리팹 인스턴스를 이동시킴.
  - 전투가 끝나면 프리팹 인스턴스만 파괴.
```c#
public class MapGenerator : MonoBehaviour
{
	//인스펙터 상에서 미리 세팅
	public Vector2Int[] enemyPositions;
	public Vector2Int[] partyPositions; 

	void Awake()
	{
		//맵 생성
		GenerateMap(맵 데이터);

		//적군, 파티 유닛 프리팹 인스턴스 생성
		for(int i = 0; i < 파티 유닛 수; i++)
			GenerateModelOnMap(파티 유닛[i], partyPositions[i]);
		for(int i = 0; i < 적군 유닛 수; i++)
			GenerateModelOnMap(적군 유닛[i], enemyPositions[i]);
	}

	//해당 unit 전용 프리팹 인스턴스를 position에 배치 후 unit에 연결. 
	public void GenerateModelOnMap(Unit unit, Vector2Int position);
	
	//배열 형식으로 제작된 맵 데이터를 받아 맵 위의 지형물 등을 생성
	public void GenerateMap(맵 데이터);
}
```

**Comment by unagi11** [comment]
전투방의 MVC 패턴 구조에서
Controller가 왜 BattleManager인지 이해가 안됩니다.
제가 생각하기에 런타임중 데이터를 처리하는건 지금 BattleManager라고 생각하는데,

인디케이터를 생성하는 BattleUI가 **Viewer**
클릭, 엔터 트리거 등을 처리하는 인디케이터와 같은것이 **Controller** 가 되고, 
맵 제네레이팅 같은 데이터 관리와 내부 처리는 현재 **BattleManager**등의 ~Manager가 처리하는게 아닌가요??

MapGenerator.cs는 ~Manager와 같은 기능을 한다고 생각하는데요.

**Comment by unagi11** [comment]
MVC 패턴 구조를 확실히 하는것에는 동의합니다.
다만 추상적인 개념을 실제 현재 코드에 어떻게 적용할지 아직 감이 안잡히는군요..

**Comment by NaTure77** [comment]
의견 감사합니다.
Controller의 역할이 모호해서 MVC 모델에 대해 다시 검색해보니, 일반적으로 "사용자 입력"을 받는쪽이 Controller네요.(지금 구조는 View와 Controller가 합쳐져 있는 MVC1에 가까워 보입니다.)

MapGenerator 기능이 추가된다면 기존 BattleManager에 두는것이 맞겠군요.
View 갱신 코드도 BattleManager에서 호출하는게 아니라 BattleUI에서 직접 처리하도록 해야겠네요.

두번째 제안사항에 대해서도 의견을 얻고싶습니다.

**Comment by unagi11** [comment]
mvc1에 가까운게 맞는거같습니다. 하지만 위에 이슈처럼 모델을 컨트롤러-뷰와 분리하는 작업이 필요할거같습니다.
이때 모델은 컨트롤러-뷰의 존재를 모르고 오직 컨트롤러-뷰가 모델의 변화를 모니터링해야 한다고 하네요
