### ISSUE TITLE
UnitAction.cs

### ISSUE THREAD

**Issue by unagi11** [TeamJelly/project21#32]
함수 원형
```C#
bool 액션 (Unit From, Tile To, string Option) { 

}
```

"{action1} [param1] [param2] ... [param n] ; {action2} [param1] [param2] ;  ..."
"attack 10 ; move 5 3 ;"
{ "actionName": "attack", "parameters": "10" }

Unit Status의 Dictionary화
```
Unit["strength"]
```

unit[varaible]

"attack strength + 1 ;"
"attack strength +1 ;"
이국오늘 오후 9:17
attack strength *2 +1
null *1 +0
제환오늘 오후 9:19
+1 *2
+1
*2

Attack(, ,Unit.strength * 2

"Attack, strength *2 +10"

Pa

스킬

내 힘에 2배에 달하는 수치의 턴동안 독효과를 부여합니다.
GiveEffect(user, giveToTile,

10턴동안 독효과를 부여합니다.
GiveEffect(user, giveToTile, "독,10");

피해
회복
사망 
이동 Move(user, moveToTile);
효과부여

GiveEffect(user, giveToTile, "기절");

레벨업
소환

능력치변경?

**Comment by JeHwanYoo** [comment]
관리 되지 않은 이슈라 닫습니다.
