### ISSUE TITLE
AI 설계

### ISSUE THREAD

**Issue by unagi11** [TeamJelly/project21#36]
현재 유닛의 할수있는 행동을 모두 파악해서
모든 경우의 수를 계산하는 단계
1. 내가 이동가능한 위치
2. 내가 공격가능한 위치
+. 공격했을때 몇의 데미지를 입힐수 있는가?

타겟을 정하는 우선순위
1. 가장 가까운
2. 가장 먼
3. 가장 약한
4. 가장 큰 데미지를 입힐수 있는
5. 가장 많은
6. 현재 체력이 적은

1. 적
2. 아군
3. 파티

Ai
1 스킬 - 약한 적에게 사용
2 스킬 - 강한 적에게 사용
3 스킬 - 가장 가까운 적에게 사용

사용 가능한 스킬이 없을 경우
1. 가만히 있는다.
2. 적에게 가까워진다.
3. 적에게 멀어진다.

**Comment by unagi11** [comment]
https://app.diagrams.net/#G1Sa7_eKco9DtkzQPi9tCXhwVXQhjrJa3I

**Comment by JeHwanYoo** [comment]
관리 되지 않은 이슈라 닫습니다.
