### ISSUE TITLE
스킬 클래스명 변경제안

### ISSUE THREAD

**Issue by unagi11** [TeamJelly/project21#37]
현재 스킬 클래스 명이 Skill_XXX.cs라고 되어있는데 직접 클래스를 들어가거나 기획표를 찾아보지 않으면
무슨 스킬인지 알수가 없다.

리펙토링 제안
> 번호_스킬명 ex.) 001_베기.cs
로 코드-클래스명을 바꾼다.

**Comment by JeHwanYoo** [comment]
관리 되지 않은 이슈라 닫습니다.
