### ISSUE TITLE
비전투시 유닛 컨트롤

### ISSUE THREAD

**Issue by NaTure77** [TeamJelly/project21#45]

**Comment by NaTure77** [comment]
해결해야 할 Issue
- 자유롭게 움직이게 하기 위해서는 맵 공간에 전부 타일이 깔려 있어야 함.
- 비전투시의 UI 구상
- 대표 유닛을 선택하는 UI 구상

예상되는 Logic
1. 이동하고자 하는 타일 클릭
2. 대표 유닛이 이동. (이동 알고리즘 사용)
3. 타일 위에 유물 or 아이템이 있으면 획득. (아이템은 빈 슬롯이 있을 경우만.)

**Comment by unagi11** [comment]
전투시와 비전투시를 나누는 변수가 필요할거같음
```cs
bool inBattle = true;
```
