### ISSUE TITLE
프로젝트 기본 세팅

### ISSUE THREAD

**Issue by JeHwanYoo** [TeamJelly/project21#6]
- [x] Bolt 설치
- [x] 디렉토리 설정
- [x] .gitignore 추가
- [x] 프로젝트 병합
- [x] Pull Request

매크로 작성 시
Flow Macro -> Macros/Flow Macros
State Macro -> Macros/State Macros

에 저장해주세요.

**Comment by JeHwanYoo** [comment]
.gitignore는 기존에 있는것을 확인했습니다.

**Comment by unagi11** [comment]
Bolt플러그인 파일을 제외하기 .gitignore를 수정합니다.
https://docs.unity3d.com/2019.3/Documentation/Manual/bolt-version-control.html

**Comment by JeHwanYoo** [comment]
@unagi11 테스트하고 merge 하도록 하겠습니다.
