### ISSUE TITLE
UI 구상

### ISSUE THREAD

**Issue by NaTure77** [TeamJelly/project21#9]
- **영웅 선택**
![image.png](https://images.zenhubusercontent.com/5fe1d9cbf5b04008dddc051a/cb73b7c1-905c-4e7d-996f-502cf41cc66c)

1. 파티에 추가할 수 있는 영웅 리스트
2. 영웅 List에서 선택한 영웅의 정보. 고용 버튼을 누르면(또는 리스트에서 더블클릭) 파티에 추가됨.
3. 현재까지 추가된 파티원 목록. x버튼을 누르면 고용 취소.
4. 이전 화면으로 돌아감. (메인 화면)
5. 다음 화면으로 넘어감. (난이도 설정 화면)

- **난이도 설정**
![image](https://user-images.githubusercontent.com/18459135/103283861-08f96080-4a1d-11eb-8632-d89ad41a65db.png)

1. 난이도별 설명이 적혀있는 버튼
2. 이전 화면으로 돌아감(영웅 선택 화면)
3. 선택된 난이도로 게임 시작

- **메인 게임(전투)** - 에픽세븐 참조

![image.png](https://images.zenhubusercontent.com/5fe1d9cbf5b04008dddc051a/1ccded41-6f84-442d-926d-b719166658fb)

1. 파티 각각의 이름, 체력, 이미지 등을 표시
2. 메뉴 버튼
3. 유닛 턴 순서 표시기
4. 파티 턴 표시
5. 현재 턴을 수행할 유닛의 정보
6. 유닛 이동 
7. 유닛 스킬 선택 목록
8. 유닛 아이템 선택 목록
9. 턴 종료

- **상점**

- **스킬/아이템/유물 획득**

- **게임 승리/ 패배** 

- **환경설정**

- **영웅 정보 열람**

- **현재 층 방 연결화면**

**Comment by JeHwanYoo** [comment]
0.1.0 milestone에 등록해주세요.

우측 메뉴에 있습니다.

@NaTure77

**Comment by unagi11** [comment]
확인완료 피드백 (메인전투)
1. 1번의 파티 전체의 이름이나 체력은 필요없고, 유닛 각각의 초상화와 체력을 보여주면 좋을거같습니다. 아군은 필수 적군도 있으면 좋고.
2. 5번의 현재 턴을 수행할 유닛의 정보 말고도 따로 플레이어가 선택한 (적이라던가)유닛의 정보를 보는거도 필요할거 같습니다.
3. 7, 8번이 스킬, 아이템 버튼만 있고 버튼을 누르면 사용할수 있는 스킬과 아이템 목록과 돌아가기 버튼이 나타났으면 좋겠습니다. 유닛마다 가지고 있는 스킬 개수가 다를수 있다고 생각합니다.

@NaTure77

**Comment by NaTure77** [comment]
@unagi11 @shiromarisa 
피드백 적용하였습니다.

**메인 게임(전투) UI 수정안**

**변경사항**
- 파티 전체 이름, 체력 -> 상단에 유닛 각각의 초상화와 체력 표시(1)
- 선택 유닛의 정보 표시 팝업창 추가(5)
- 보유 유물 창 추가(7)
- 이동 버튼 제거(타일 맵상에 표시될 가이드라인 클릭으로 대체 가능할 것 같습니다.)
- 하단부 배치 수정

**이미지**
![image](https://user-images.githubusercontent.com/18459135/103355213-0c5e1c00-4af1-11eb-9e98-9c1cd837f9b4.png)




1. 유닛들의 초상화, 체력 표시
2. 메뉴 버튼
3. 유닛 턴 순서 표시기
4. 유닛의 턴 알림
5. 마우스로 클릭한 유닛의 정보창(활성화, 비활성화 가능)
6. 현재 턴 유닛의 초상화, 체력 표시
7. 현재 턴 유닛의 보유 유물
8. 현재 턴 유닛의 보유 스킬
9. 현재 턴 유닛의 보유 아이템
10. 턴 종료

**Comment by NaTure77** [comment]
**메인 게임(전투) UI 수정안**

**변경사항**
- 상대방 정보 제거
- 유닛 턴 표시기 제거(SPEED 값으로 대체)
- Vs글자 및 불필요한 UI 제거
- 유닛들 초상화 상단에서 좌측으로 이동(ActionRate 기준 정렬)
- 유닛 HP 표시 숫자로 변경
- 현재 턴 유닛 보유 유물 -> 유닛 정보창으로 이동
- 맵 추가


![image](https://user-images.githubusercontent.com/18459135/103756070-2d26f400-5052-11eb-8a61-35efc4086dac.png)

1. 파티 유닛들 정보
2. 맵.
2-1. 이동 가능 타일 표시. 누르면 유닛 이동.
3. 유닛 정보창. 1번 항목 클릭시 활성화. 보유 유물정보 표시(예정)
4. 메뉴 버튼
5. 현재 턴 유닛의 정보
6. 현재 턴 유닛의 보유 스킬
7. 현재 턴 유닛의 보유 아이템
8. 턴 종료

**Comment by NaTure77** [comment]
**메인 게임(전투) UI 수정안**

**주요 변경사항**
- 맵 크기 확대
-  스킬, 아이템, 턴종료 UI 중앙 하단에서 좌측 하단으로 재배치.
- 맵에서 유닛 클릭시 정보창 활성화
- 현재 턴 유닛을 나타내는 테두리 추가

![image](https://user-images.githubusercontent.com/18459135/104002486-7f981a00-51e4-11eb-854f-fa22227e1669.png)

1. 파티 유닛들 정보. 현재 턴 유닛은 노란 테두리로 표시.
2. 맵.
2-1. 이동 가능 타일 표시. 타일 표시기(노란색)가 표시된 타일을 누르면 유닛 이동.
3. 유닛 정보창. 1번 항목 또는 맵의 유닛 클릭시 활성화. 보유 유물정보 표시(예정)
4. 메뉴 버튼
5. 현재 턴 유닛의 정보
6. 현재 턴 유닛의 보유 스킬
7. 현재 턴 유닛의 보유 아이템
8. 턴 종료

**Comment by JeHwanYoo** [comment]
관리 되지 않은 이슈라 닫습니다.
